name: Test Caller Workflow

on:
  push:
    branches:
      - test1
      - test2

jobs:
  call-reusable:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Environment Variables
        id: set-env-vars
        run: |
          if [ "${{ github.ref_name }}" == "test1" ]; then
            echo "env_name=Test1 Environment" >> $GITHUB_ENV
            echo "service=test1-service" >> $GITHUB_ENV
            echo "domain=test1.example.com" >> $GITHUB_ENV
            echo "base_url=https://test1.example.com" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "test2" ]; then
            echo "env_name=Test2 Environment" >> $GITHUB_ENV
            echo "service=test2-service" >> $GITHUB_ENV
            echo "domain=test2.example.com" >> $GITHUB_ENV
            echo "base_url=https://test2.example.com" >> $GITHUB_ENV
          else
            echo "Unknown branch: ${GITHUB_REF_NAME}"
            exit 1
          fi

      - name: Call Reusable Workflow
        uses: aguilalv/cloudmailin/.github/workflows/reusable-deployment.yml@staging 
        with:
          environment: ${{ env.env_name }}
          service: ${{ env.service }}
          domain: ${{ env.domain }}
          base_url: ${{ env.base_url }}

