name: Debug Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
      domain:
        required: true
        type: string
      base_url:
        required: true
        type: string

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print Variables to Summary
        run: |
          echo "## Debugging Inputs" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- Service: ${{ inputs.service }}" >> $GITHUB_STEP_SUMMARY
          echo "- Domain: ${{ inputs.domain }}" >> $GITHUB_STEP_SUMMARY
          echo "- Base URL: ${{ inputs.base_url }}" >> $GITHUB_STEP_SUMMARY
